// Generated by Wrangler on Sun Jun 16 2024 22:43:25 GMT+0100 (Irish Standard Time)
// by running `wrangler types`

interface Env {
	TOKEN: string;
	BUDGET: string;
	ACCOUNT: string;
	RATE_APR: string;
	CALCULATED: string;
	PAYOUT: string;
}
